In [11]:
import numpy as np

natural = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(natural)

[ 1  2  3  4  5  6  7  8  9 10]


1. одновимірний масив (вектор) з першими 10-ма натуральними числами

In [12]:
mx = np.zeros((3,3))
print(mx)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. двовимірний масив (матрицю) розміром 3x3, заповніть його нулями

In [13]:
import random

mx = [[random.randint(1, 10) for j in range(5)] for i in range(5)]
for i in range(5):
  print(mx[i])

[1, 2, 8, 7, 6]
[6, 8, 7, 7, 8]
[10, 9, 3, 8, 8]
[5, 10, 5, 6, 5]
[5, 10, 6, 5, 5]


 3. масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10

In [14]:
#mx = [[random.random() for j in range(4)] for i in range(4)]

mx= [[round(random.random(), 5) for j in range(4)] for i in range(4)]
for i in range(4):
  print(mx[i])

[0.19473, 0.41564, 0.67674, 0.75821]
[0.67114, 0.98625, 0.32968, 0.22103]
[0.91858, 0.28471, 0.67896, 0.51633]
[0.88582, 0.77489, 0.60449, 0.62904]


4. масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1

In [15]:
aa = np.array([random.randint(1, 10) for _ in range(5)])
bb = np.array([random.randint(1, 10) for _ in range(5)])

print ("вектор a", aa)
print ("вектор b",bb)
print ("додавання", aa+bb)
print ("віднімання", aa-bb)
print ("добуток", aa*bb)

вектор a [ 4 10  2  7 10]
вектор b [ 5  8 10  5  3]
додавання [ 9 18 12 12 13]
віднімання [-1  2 -8  2  7]
добуток [20 80 20 35 30]


5. два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
виконати операції
+ додавання,
+ віднімання та
+ множення.

In [16]:
import random
aa = np.array([random.randint(1, 20) for _ in range(7)])
bb = np.array([random.randint(1, 30) for _ in range(7)])
print ("вектор a", aa)
print ("вектор b", bb)
print(np.dot(aa, bb))

вектор a [15  5 19  3 11  5 13]
вектор b [ 1  2  4  9  2 21 29]
632


6. два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток

In [17]:
a = np.random.randint(1, 11, (2, 2))
print(a)

b = np.random.randint(1, 11, (2, 3))
print(b)

c = np.dot(a, b)
print(c)

[[4 7]
 [5 6]]
[[ 2  9  5]
 [ 6 10  7]]
[[ 50 106  69]
 [ 46 105  67]]


7. дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою

In [22]:
a = np.random.randint(1, 11, (3, 3))
print(a)

a_inv = np.linalg.inv(a)
#print(a_inv)

a_inv_round = np.round(a_inv, 4)
print(a_inv_round)

[[ 9  3  8]
 [ 5 10  6]
 [10  4  5]]
[[-0.0864 -0.0565  0.206 ]
 [-0.1163  0.1163  0.0465]
 [ 0.2658  0.0199 -0.2492]]


8. матриця розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [27]:
a = np.random.random((4, 4))
#print(a)
r_a = np.round(a, 2)
b = a.T
r_b = r_a.T
#print(b)

print(r_a)
print(r_b)

[[0.54 0.29 0.81 0.82]
 [0.93 0.66 0.33 0.97]
 [0.89 0.51 0.54 0.27]
 [0.58 0.32 0.81 0.32]]
[[0.54 0.93 0.89 0.58]
 [0.29 0.66 0.51 0.32]
 [0.81 0.33 0.54 0.81]
 [0.82 0.97 0.27 0.32]]


9. матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [29]:
mtx = np.random.randint(1, 11, (3, 4))
print(mtx)

vec = np.random.randint(1, 11, (4))
print(vec)

c = np.dot(mtx, vec)
print(c)

[[ 4  2  5  3]
 [ 1  9 10  6]
 [ 5  3  7  3]]
[6 7 9 3]
[ 92 177 123]


10. матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [45]:
a = np.random.random((2, 3))
b = np.random.random(3)
print(b)
print(a)
c = np.dot(a, b)
print(c)

[0.03347251 0.74592489 0.18534792]
[[0.64371756 0.88391162 0.90013025]
 [0.88778247 0.906978   0.65629265]]
[0.84771579 0.82789626]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [36]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

print(a)
print(b)
c = a * b
print(c)

[[10  4]
 [ 8  3]]
[[ 1 10]
 [ 6  3]]
[[10 40]
 [48  9]]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [42]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))

print(a)
print(b)
c = np.dot(a, b)
print(c)
d = a @ b
print(d)

[[8 1]
 [7 8]]
[[1 3]
 [3 9]]
[[11 33]
 [31 93]]
[[11 33]
 [31 93]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [41]:
a = np.random.randint(1, 101, (5, 5))
print(a)
print(a.sum())

[[13 50 75 60 73]
 [34 81 74 70 10]
 [60 52  9 50 42]
 [16 21 66 14 74]
 [89 18 49 92 54]]
1246


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [44]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))

print(a)
print(b)
c = np.subtract(a, b)
print(c)

[[ 5  3  1  2]
 [ 2  6  2  9]
 [ 1  8 10  7]
 [ 1  9  2 10]]
[[10  4  3  5]
 [ 9  5  1  3]
 [ 9  3  5  3]
 [ 3  3  3  6]]
[[-5 -1 -2 -3]
 [-7  1  1  6]
 [-8  5  5  4]
 [-2  6 -1  4]]


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю

In [55]:
a = np.random.random((3, 3))
print(np.round(a,2))
b = np.sum(a, axis=1)
print(np.round(b,2))

[[0.65 0.42 0.18]
 [0.41 0.2  0.46]
 [0.01 0.38 0.96]]
[1.25 1.06 1.36]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [59]:
a = np.random.randint(-10, 10, (3, 4))
print(a)
b = a**2
print(b)
c = np.power(a,2)
print(c)

[[  4  -5   6  -1]
 [ -1  -2   6   9]
 [ -6   1 -10   1]]
[[ 16  25  36   1]
 [  1   4  36  81]
 [ 36   1 100   1]]
[[ 16  25  36   1]
 [  1   4  36  81]
 [ 36   1 100   1]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [69]:
vec = np.random.randint(1, 51, 4)
print(vec)
bv = np.sqrt(vec)
print(np.round(bv,2))

[27 28 46 26]
[5.2  5.29 6.78 5.1 ]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.